♻️ Tidy models
TwinePlatform/twine-api pull request #386
Opened 2019-04-04 10:38 UTC by astroash

2019-04-05 12:48 UTC, eliasmalik requested changes

2019-04-05 12:48 UTC, eliascodes commented on src/auth/strategies/standard/validate.ts
> +import Permissions from '../../../models/__tests__/permission';
Errrrr...?

2019-04-05 12:48 UTC, eliascodes commented on src/models/__tests__/community_business.test.integration.ts
> +import moment = require('moment');
```suggestion
import * as moment from 'moment';
```

2019-04-05 12:48 UTC, eliascodes commented on src/models/__tests__/permission.ts
>  import { uniqWith, equals } from 'ramda';
Why is this file in a `__tests__` directory?

2019-04-05 12:48 UTC, eliascodes commented on src/models/__tests__/token.test.integration.ts
> +describe('User Model', () => {
Change

2019-04-05 12:48 UTC, eliascodes commented on src/models/__tests__/token.test.integration.ts
> +  describe('createConfirmAddRoleToken', () => {
Resolve this comment if all these tests are cut and pasted from the old user model tests without any changes (except for re-naming).

2019-04-05 12:48 UTC, eliascodes commented on src/models/__tests__/volunteer.test.integration.ts
> +import moment = require('moment');
```suggestion
import * as moment from 'moment';
```

2019-04-05 12:48 UTC, eliascodes commented on src/models/token.ts
> +import moment = require('moment');
```suggestion
import * as moment from 'moment';
```

2019-04-11 07:58 UTC, astroash commented
closing as this has been recreated in mono https://github.com/TwinePlatform/twine-main/pull/11

2019-04-11 07:58 UTC, closed without merging